name       : cmatrix
version    : '1.2'
release    : 5
homepage   : http://www.asty.org/cmatrix/
source     :
    - https://github.com/abishekvashok/cmatrix/archive/1.2.tar.gz : 6b0b9aff4585147843c4cf8a8c9c6048500f66dc4887a38922197dfa326b57c8
license    : GPL-2.0-or-later
component  : desktop
summary    : Simulates the display from "The Matrix".
description: |
    Simulates the display from "The Matrix".
setup      : |
    ./configure --prefix=/usr
build      : |
    %make
install    : |
    %make_install
