name       : cmatrix
version    : 1.2a
release    : 4
homepage   : http://www.asty.org/cmatrix/
source     :
    - https://sourceforge.net/projects/cmatrix/files/latest/download : 1fa6e6caea254b6fe70a492efddc1b40ad7ccb950a5adfd80df75b640577064c
license    : GPL-2.0-or-later
component  : desktop
summary    : Simulates the display from "The Matrix".
description: |
    Simulates the display from "The Matrix".
setup      : |
    ./configure --prefix=/usr
build      : |
    %make
install    : |
    %make_install
