name       : cmatrix
version    : 1.2a
release    : 1
homepage   : http://www.asty.org/cmatrix/
source     :
    - http://www.asty.org/cmatrix/dist/cmatrix-1.2a.tar.gz : 1fa6e6caea254b6fe70a492efddc1b40ad7ccb950a5adfd80df75b640577064c
license    : GPL-2.0
summary    : Simulates the display from "The Matrix".
description: |
    Simulates the display from "The Matrix".
setup      : |
    ./configure --prefix=/usr
build      : |
    %make
install    : |
    %make_install